plugins {
    id 'java'
    id 'org.wpilib.WPILibRepositoriesPlugin' version '2027.0.0'
}

group = 'team1306'
ext.wpilibVersion = "2027.+"

if (project.hasProperty('releaseMode')) {
    wpilibRepositories.addAllReleaseRepositories(project)
} else {
    wpilibRepositories.addAllDevelopmentRepositories(project)
}
wpilibRepositories.use2027Repos()

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly "org.wpilib:commands3-java:2027.0.0-alpha-6"
}


java {
    withSourcesJar()
    withJavadocJar()

    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
var javaVersion = "25"


test {
    useJUnitPlatform()
}
